# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: O:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: O:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: o:/engs128/lab5/lab5.srcs/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
